learning_rate: 0.010098
feature_fraction: 0.2334023
bagging_fraction: 0.5455751
min_data_in_leaf: 0
num_leaves: 34
max_bin: 255.0165805
'y': 0.8660975
dob: 155
eol: .na.integer
error.message: .na.character
exec.time: 38.746
ei: -0.0001558
error.model: .na.character
train.time: 0.959
prop.type: infill_ei
propose.time: 1.809
se: 0.0009054
mean: 0.8653812
num_iterations: 988
iteracion: 179
script: lightgbm_BO
